// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProjetoJogos.Dados;

#nullable disable

namespace ProjetoJogos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoJogos.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoLancamento")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("ProjetoJogos.Models.JogoPlataforma", b =>
                {
                    b.Property<int>("JogoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PlataformaId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("JogoId", "PlataformaId");

                    b.HasIndex("PlataformaId");

                    b.ToTable("JogosPlataformas");
                });

            modelBuilder.Entity("ProjetoJogos.Models.Plataforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Plataformas");
                });

            modelBuilder.Entity("ProjetoJogos.Models.JogoPlataforma", b =>
                {
                    b.HasOne("ProjetoJogos.Models.Jogo", "Jogo")
                        .WithMany("JogosPlataformas")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoJogos.Models.Plataforma", "Plataforma")
                        .WithMany("JogosPlataformas")
                        .HasForeignKey("PlataformaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Plataforma");
                });

            modelBuilder.Entity("ProjetoJogos.Models.Jogo", b =>
                {
                    b.Navigation("JogosPlataformas");
                });

            modelBuilder.Entity("ProjetoJogos.Models.Plataforma", b =>
                {
                    b.Navigation("JogosPlataformas");
                });
#pragma warning restore 612, 618
        }
    }
}
